version: '2'

services:
  web2py:
    build: .
    image: smithmicro/web2py
    command: uwsgi
    environment:
      - WEB2PY_PASSWORD=password
      - WEB2PY_VERSION=
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./keys:/keys:ro
    depends_on:
      - web2py
    ports:
      - 8080:80
      - 8443:443
